/**
 * Fax.to REST API client for Android
 * This is Fax.to REST API client for Android.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2003Created {
  
  @SerializedName("date")
  private Date date = null;
  @SerializedName("timezone_type")
  private Integer timezoneType = null;
  @SerializedName("timezone")
  private String timezone = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getDate() {
    return date;
  }
  public void setDate(Date date) {
    this.date = date;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTimezoneType() {
    return timezoneType;
  }
  public void setTimezoneType(Integer timezoneType) {
    this.timezoneType = timezoneType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTimezone() {
    return timezone;
  }
  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003Created inlineResponse2003Created = (InlineResponse2003Created) o;
    return (this.date == null ? inlineResponse2003Created.date == null : this.date.equals(inlineResponse2003Created.date)) &&
        (this.timezoneType == null ? inlineResponse2003Created.timezoneType == null : this.timezoneType.equals(inlineResponse2003Created.timezoneType)) &&
        (this.timezone == null ? inlineResponse2003Created.timezone == null : this.timezone.equals(inlineResponse2003Created.timezone));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.date == null ? 0: this.date.hashCode());
    result = 31 * result + (this.timezoneType == null ? 0: this.timezoneType.hashCode());
    result = 31 * result + (this.timezone == null ? 0: this.timezone.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003Created {\n");
    
    sb.append("  date: ").append(date).append("\n");
    sb.append("  timezoneType: ").append(timezoneType).append("\n");
    sb.append("  timezone: ").append(timezone).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
