/**
 * Fax.to REST API client for Android
 * This is Fax.to REST API client for Android.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2002 {
  
  @SerializedName("status")
  private String status = null;
  @SerializedName("message")
  private String message = null;
  @SerializedName("user_cash_balance")
  private BigDecimal userCashBalance = null;

  /**
   * The status of the API request
   **/
  @ApiModelProperty(value = "The status of the API request")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * Display message
   **/
  @ApiModelProperty(value = "Display message")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }

  /**
   * Remaining cash balance
   **/
  @ApiModelProperty(value = "Remaining cash balance")
  public BigDecimal getUserCashBalance() {
    return userCashBalance;
  }
  public void setUserCashBalance(BigDecimal userCashBalance) {
    this.userCashBalance = userCashBalance;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return (this.status == null ? inlineResponse2002.status == null : this.status.equals(inlineResponse2002.status)) &&
        (this.message == null ? inlineResponse2002.message == null : this.message.equals(inlineResponse2002.message)) &&
        (this.userCashBalance == null ? inlineResponse2002.userCashBalance == null : this.userCashBalance.equals(inlineResponse2002.userCashBalance));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    result = 31 * result + (this.userCashBalance == null ? 0: this.userCashBalance.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    
    sb.append("  status: ").append(status).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("  userCashBalance: ").append(userCashBalance).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
