/**
 * Fax.to REST API client for Android
 * This is Fax.to REST API client for Android.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2004Inbox;
import io.swagger.client.model.InlineResponse2004Meta;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2004 {
  
  @SerializedName("status")
  private String status = null;
  @SerializedName("inbox")
  private List<InlineResponse2004Inbox> inbox = null;
  @SerializedName("meta")
  private InlineResponse2004Meta meta = null;

  /**
   * The status of the API request
   **/
  @ApiModelProperty(value = "The status of the API request")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * The faxes received by a certain user
   **/
  @ApiModelProperty(value = "The faxes received by a certain user")
  public List<InlineResponse2004Inbox> getInbox() {
    return inbox;
  }
  public void setInbox(List<InlineResponse2004Inbox> inbox) {
    this.inbox = inbox;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public InlineResponse2004Meta getMeta() {
    return meta;
  }
  public void setMeta(InlineResponse2004Meta meta) {
    this.meta = meta;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inlineResponse2004 = (InlineResponse2004) o;
    return (this.status == null ? inlineResponse2004.status == null : this.status.equals(inlineResponse2004.status)) &&
        (this.inbox == null ? inlineResponse2004.inbox == null : this.inbox.equals(inlineResponse2004.inbox)) &&
        (this.meta == null ? inlineResponse2004.meta == null : this.meta.equals(inlineResponse2004.meta));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.inbox == null ? 0: this.inbox.hashCode());
    result = 31 * result + (this.meta == null ? 0: this.meta.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");
    
    sb.append("  status: ").append(status).append("\n");
    sb.append("  inbox: ").append(inbox).append("\n");
    sb.append("  meta: ").append(meta).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
