/**
 * Fax.to REST API client for Android
 * This is Fax.to REST API client for Android.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20016Data {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("did_id")
  private Integer didId = null;
  @SerializedName("did_group_id")
  private Integer didGroupId = null;
  @SerializedName("country_code")
  private String countryCode = null;
  @SerializedName("city_name")
  private String cityName = null;
  @SerializedName("area_code")
  private String areaCode = null;
  @SerializedName("number")
  private String number = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("trunk_id")
  private Integer trunkId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDidId() {
    return didId;
  }
  public void setDidId(Integer didId) {
    this.didId = didId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDidGroupId() {
    return didGroupId;
  }
  public void setDidGroupId(Integer didGroupId) {
    this.didGroupId = didGroupId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountryCode() {
    return countryCode;
  }
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCityName() {
    return cityName;
  }
  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAreaCode() {
    return areaCode;
  }
  public void setAreaCode(String areaCode) {
    this.areaCode = areaCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNumber() {
    return number;
  }
  public void setNumber(String number) {
    this.number = number;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTrunkId() {
    return trunkId;
  }
  public void setTrunkId(Integer trunkId) {
    this.trunkId = trunkId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20016Data inlineResponse20016Data = (InlineResponse20016Data) o;
    return (this.id == null ? inlineResponse20016Data.id == null : this.id.equals(inlineResponse20016Data.id)) &&
        (this.didId == null ? inlineResponse20016Data.didId == null : this.didId.equals(inlineResponse20016Data.didId)) &&
        (this.didGroupId == null ? inlineResponse20016Data.didGroupId == null : this.didGroupId.equals(inlineResponse20016Data.didGroupId)) &&
        (this.countryCode == null ? inlineResponse20016Data.countryCode == null : this.countryCode.equals(inlineResponse20016Data.countryCode)) &&
        (this.cityName == null ? inlineResponse20016Data.cityName == null : this.cityName.equals(inlineResponse20016Data.cityName)) &&
        (this.areaCode == null ? inlineResponse20016Data.areaCode == null : this.areaCode.equals(inlineResponse20016Data.areaCode)) &&
        (this.number == null ? inlineResponse20016Data.number == null : this.number.equals(inlineResponse20016Data.number)) &&
        (this.type == null ? inlineResponse20016Data.type == null : this.type.equals(inlineResponse20016Data.type)) &&
        (this.trunkId == null ? inlineResponse20016Data.trunkId == null : this.trunkId.equals(inlineResponse20016Data.trunkId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.didId == null ? 0: this.didId.hashCode());
    result = 31 * result + (this.didGroupId == null ? 0: this.didGroupId.hashCode());
    result = 31 * result + (this.countryCode == null ? 0: this.countryCode.hashCode());
    result = 31 * result + (this.cityName == null ? 0: this.cityName.hashCode());
    result = 31 * result + (this.areaCode == null ? 0: this.areaCode.hashCode());
    result = 31 * result + (this.number == null ? 0: this.number.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.trunkId == null ? 0: this.trunkId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20016Data {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  didId: ").append(didId).append("\n");
    sb.append("  didGroupId: ").append(didGroupId).append("\n");
    sb.append("  countryCode: ").append(countryCode).append("\n");
    sb.append("  cityName: ").append(cityName).append("\n");
    sb.append("  areaCode: ").append(areaCode).append("\n");
    sb.append("  number: ").append(number).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  trunkId: ").append(trunkId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
