/**
 * Fax.to REST API client for Android
 * This is Fax.to REST API client for Android.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2003Created;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2003History {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("created")
  private InlineResponse2003Created created = null;
  @SerializedName("document_id")
  private Integer documentId = null;
  @SerializedName("document")
  private String document = null;
  @SerializedName("recipient")
  private String recipient = null;
  @SerializedName("status")
  private String status = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public InlineResponse2003Created getCreated() {
    return created;
  }
  public void setCreated(InlineResponse2003Created created) {
    this.created = created;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDocumentId() {
    return documentId;
  }
  public void setDocumentId(Integer documentId) {
    this.documentId = documentId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDocument() {
    return document;
  }
  public void setDocument(String document) {
    this.document = document;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRecipient() {
    return recipient;
  }
  public void setRecipient(String recipient) {
    this.recipient = recipient;
  }

  /**
   * The status of the fax job
   **/
  @ApiModelProperty(value = "The status of the fax job")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003History inlineResponse2003History = (InlineResponse2003History) o;
    return (this.id == null ? inlineResponse2003History.id == null : this.id.equals(inlineResponse2003History.id)) &&
        (this.created == null ? inlineResponse2003History.created == null : this.created.equals(inlineResponse2003History.created)) &&
        (this.documentId == null ? inlineResponse2003History.documentId == null : this.documentId.equals(inlineResponse2003History.documentId)) &&
        (this.document == null ? inlineResponse2003History.document == null : this.document.equals(inlineResponse2003History.document)) &&
        (this.recipient == null ? inlineResponse2003History.recipient == null : this.recipient.equals(inlineResponse2003History.recipient)) &&
        (this.status == null ? inlineResponse2003History.status == null : this.status.equals(inlineResponse2003History.status));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.created == null ? 0: this.created.hashCode());
    result = 31 * result + (this.documentId == null ? 0: this.documentId.hashCode());
    result = 31 * result + (this.document == null ? 0: this.document.hashCode());
    result = 31 * result + (this.recipient == null ? 0: this.recipient.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003History {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  created: ").append(created).append("\n");
    sb.append("  documentId: ").append(documentId).append("\n");
    sb.append("  document: ").append(document).append("\n");
    sb.append("  recipient: ").append(recipient).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
