/**
 * Fax.to REST API client for Android
 * This is Fax.to REST API client for Android.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse200 {
  
  @SerializedName("status")
  private String status = null;
  @SerializedName("fax_job_id")
  private Integer faxJobId = null;
  @SerializedName("user_cash_balance")
  private BigDecimal userCashBalance = null;
  @SerializedName("cost")
  private BigDecimal cost = null;

  /**
   * The status of the API request
   **/
  @ApiModelProperty(value = "The status of the API request")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * The id of the fax job. It is used to check the status of the fax job.
   **/
  @ApiModelProperty(value = "The id of the fax job. It is used to check the status of the fax job.")
  public Integer getFaxJobId() {
    return faxJobId;
  }
  public void setFaxJobId(Integer faxJobId) {
    this.faxJobId = faxJobId;
  }

  /**
   * The remaining cash balance
   **/
  @ApiModelProperty(value = "The remaining cash balance")
  public BigDecimal getUserCashBalance() {
    return userCashBalance;
  }
  public void setUserCashBalance(BigDecimal userCashBalance) {
    this.userCashBalance = userCashBalance;
  }

  /**
   * The cost of sending fax
   **/
  @ApiModelProperty(value = "The cost of sending fax")
  public BigDecimal getCost() {
    return cost;
  }
  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return (this.status == null ? inlineResponse200.status == null : this.status.equals(inlineResponse200.status)) &&
        (this.faxJobId == null ? inlineResponse200.faxJobId == null : this.faxJobId.equals(inlineResponse200.faxJobId)) &&
        (this.userCashBalance == null ? inlineResponse200.userCashBalance == null : this.userCashBalance.equals(inlineResponse200.userCashBalance)) &&
        (this.cost == null ? inlineResponse200.cost == null : this.cost.equals(inlineResponse200.cost));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.faxJobId == null ? 0: this.faxJobId.hashCode());
    result = 31 * result + (this.userCashBalance == null ? 0: this.userCashBalance.hashCode());
    result = 31 * result + (this.cost == null ? 0: this.cost.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("  status: ").append(status).append("\n");
    sb.append("  faxJobId: ").append(faxJobId).append("\n");
    sb.append("  userCashBalance: ").append(userCashBalance).append("\n");
    sb.append("  cost: ").append(cost).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
