/**
 * Fax.to REST API client for Android
 * This is Fax.to REST API client for Android.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20012Data {
  
  @SerializedName("country")
  private String country = null;
  @SerializedName("slug")
  private String slug = null;
  @SerializedName("a2_code")
  private String a2Code = null;
  @SerializedName("dial_code")
  private Integer dialCode = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSlug() {
    return slug;
  }
  public void setSlug(String slug) {
    this.slug = slug;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getA2Code() {
    return a2Code;
  }
  public void setA2Code(String a2Code) {
    this.a2Code = a2Code;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDialCode() {
    return dialCode;
  }
  public void setDialCode(Integer dialCode) {
    this.dialCode = dialCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20012Data inlineResponse20012Data = (InlineResponse20012Data) o;
    return (this.country == null ? inlineResponse20012Data.country == null : this.country.equals(inlineResponse20012Data.country)) &&
        (this.slug == null ? inlineResponse20012Data.slug == null : this.slug.equals(inlineResponse20012Data.slug)) &&
        (this.a2Code == null ? inlineResponse20012Data.a2Code == null : this.a2Code.equals(inlineResponse20012Data.a2Code)) &&
        (this.dialCode == null ? inlineResponse20012Data.dialCode == null : this.dialCode.equals(inlineResponse20012Data.dialCode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.slug == null ? 0: this.slug.hashCode());
    result = 31 * result + (this.a2Code == null ? 0: this.a2Code.hashCode());
    result = 31 * result + (this.dialCode == null ? 0: this.dialCode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20012Data {\n");
    
    sb.append("  country: ").append(country).append("\n");
    sb.append("  slug: ").append(slug).append("\n");
    sb.append("  a2Code: ").append(a2Code).append("\n");
    sb.append("  dialCode: ").append(dialCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
