/**
 * Fax.to REST API client for Android
 * This is Fax.to REST API client for Android.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20017Numbers {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("order_reference")
  private String orderReference = null;
  @SerializedName("country_code")
  private String countryCode = null;
  @SerializedName("country")
  private String country = null;
  @SerializedName("city_name")
  private String cityName = null;
  @SerializedName("area_code")
  private String areaCode = null;
  @SerializedName("did_group_id")
  private Integer didGroupId = null;
  @SerializedName("did_number")
  private String didNumber = null;
  @SerializedName("expiration_date")
  private Date expirationDate = null;
  @SerializedName("status")
  private String status = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrderReference() {
    return orderReference;
  }
  public void setOrderReference(String orderReference) {
    this.orderReference = orderReference;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountryCode() {
    return countryCode;
  }
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCityName() {
    return cityName;
  }
  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAreaCode() {
    return areaCode;
  }
  public void setAreaCode(String areaCode) {
    this.areaCode = areaCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDidGroupId() {
    return didGroupId;
  }
  public void setDidGroupId(Integer didGroupId) {
    this.didGroupId = didGroupId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDidNumber() {
    return didNumber;
  }
  public void setDidNumber(String didNumber) {
    this.didNumber = didNumber;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getExpirationDate() {
    return expirationDate;
  }
  public void setExpirationDate(Date expirationDate) {
    this.expirationDate = expirationDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20017Numbers inlineResponse20017Numbers = (InlineResponse20017Numbers) o;
    return (this.id == null ? inlineResponse20017Numbers.id == null : this.id.equals(inlineResponse20017Numbers.id)) &&
        (this.orderReference == null ? inlineResponse20017Numbers.orderReference == null : this.orderReference.equals(inlineResponse20017Numbers.orderReference)) &&
        (this.countryCode == null ? inlineResponse20017Numbers.countryCode == null : this.countryCode.equals(inlineResponse20017Numbers.countryCode)) &&
        (this.country == null ? inlineResponse20017Numbers.country == null : this.country.equals(inlineResponse20017Numbers.country)) &&
        (this.cityName == null ? inlineResponse20017Numbers.cityName == null : this.cityName.equals(inlineResponse20017Numbers.cityName)) &&
        (this.areaCode == null ? inlineResponse20017Numbers.areaCode == null : this.areaCode.equals(inlineResponse20017Numbers.areaCode)) &&
        (this.didGroupId == null ? inlineResponse20017Numbers.didGroupId == null : this.didGroupId.equals(inlineResponse20017Numbers.didGroupId)) &&
        (this.didNumber == null ? inlineResponse20017Numbers.didNumber == null : this.didNumber.equals(inlineResponse20017Numbers.didNumber)) &&
        (this.expirationDate == null ? inlineResponse20017Numbers.expirationDate == null : this.expirationDate.equals(inlineResponse20017Numbers.expirationDate)) &&
        (this.status == null ? inlineResponse20017Numbers.status == null : this.status.equals(inlineResponse20017Numbers.status));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.orderReference == null ? 0: this.orderReference.hashCode());
    result = 31 * result + (this.countryCode == null ? 0: this.countryCode.hashCode());
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.cityName == null ? 0: this.cityName.hashCode());
    result = 31 * result + (this.areaCode == null ? 0: this.areaCode.hashCode());
    result = 31 * result + (this.didGroupId == null ? 0: this.didGroupId.hashCode());
    result = 31 * result + (this.didNumber == null ? 0: this.didNumber.hashCode());
    result = 31 * result + (this.expirationDate == null ? 0: this.expirationDate.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20017Numbers {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  orderReference: ").append(orderReference).append("\n");
    sb.append("  countryCode: ").append(countryCode).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("  cityName: ").append(cityName).append("\n");
    sb.append("  areaCode: ").append(areaCode).append("\n");
    sb.append("  didGroupId: ").append(didGroupId).append("\n");
    sb.append("  didNumber: ").append(didNumber).append("\n");
    sb.append("  expirationDate: ").append(expirationDate).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
