/**
 * Fax.to REST API client for Android
 * This is Fax.to REST API client for Android.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2004MetaPagination;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Contains the paginations links
 **/
@ApiModel(description = "Contains the paginations links")
public class InlineResponse2004Meta {
  
  @SerializedName("pagination")
  private InlineResponse2004MetaPagination pagination = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public InlineResponse2004MetaPagination getPagination() {
    return pagination;
  }
  public void setPagination(InlineResponse2004MetaPagination pagination) {
    this.pagination = pagination;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004Meta inlineResponse2004Meta = (InlineResponse2004Meta) o;
    return (this.pagination == null ? inlineResponse2004Meta.pagination == null : this.pagination.equals(inlineResponse2004Meta.pagination));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.pagination == null ? 0: this.pagination.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004Meta {\n");
    
    sb.append("  pagination: ").append(pagination).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
